### PR TITLE
Release DTDL v4

### PR DESCRIPTION
**Pull request by jrdouceur**

### CODE REVIEW

**Review by lt72 — DISMISSED** [review]

**Review by rido-min — APPROVED** [review]
- The first table in the README should include a note explaining where v4 can be used (likely AIO)
- The models shown in v4 MD files should target v4
- The `requirements` extension name is odd, it should be `required`
- Surprised we are making changes to v2 and v3 folders, those should be lock-down as those specs are already released.
- For the new context specifiers, when appending `#limitless`, does it require an update to the DTMI spec?
- Can we drop iotcentral support in v4?

**Comment by jrdouceur** [comment]
> * The first table in the README should include a note explaining where v4 can be used (likely AIO)

Updated.

> * The models shown in v4 MD files should target v4

I do not see any non-v4 models in v4 MD files.

> * The `requirements` extension name is odd, it should be `required`

Extensions have always been named with nouns, e.g., "historization", "annotation", and "overriding".  The name "requirement" is consistent with this practice.

> * Surprised we are making changes to v2 and v3 folders, those should be lock-down as those specs are already released.

The folders are not locked down; only the language is locked down.  According to our language-versioning rules, we can make point releases that do not change the validation conditions of a released language version.

The changes in these folders fix broken links, fix indentation, clarify some specification conditions, add supplemental validation cases, address a documentation issue, and reword some generated prose to make it easier to programmatically differentiate between v2/v3 rules and v4 rules.

> * For the new context specifiers, when appending `#limitless`, does it require an update to the DTMI spec?

Updated.

> * Can we drop iotcentral support in v4?

iotcentral is not even supported in v3.

**Comment by jrdouceur** [comment]
> > * The models shown in v4 MD files should target v4
>
> I do not see any non-v4 models in v4 MD files.

But there was a v3 model in the top-level README.  Now updated to v4.

**Comment by rido-min** [comment]
> I do not see any non-v4 models in v4 MD files.

eg

https://github.com/Azure/opendigitaltwins-dtdl/blob/7033bec66b570a5c9bfa14a9191d306f2bb3ae3f/DTDL/v4/DTDL.mqtt.v2.md?plain=1#L122

**Comment by rido-min** [comment]
> iotcentral is not even supported in v3.

https://github.com/Azure/opendigitaltwins-dtdl/blob/7033bec66b570a5c9bfa14a9191d306f2bb3ae3f/DTDL/v4/DTDL.Extensions.md?plain=1#L124

**Comment by rido-min** [comment]
> The name "requirement" is consistent with this practice.

`requirement` has a meaning in software development. This might be a good exception to the _nouns_ rule. just a nit though..

**Comment by jrdouceur** [comment]
> > I do not see any non-v4 models in v4 MD files.
> 
> eg
> 
> https://github.com/Azure/opendigitaltwins-dtdl/blob/7033bec66b570a5c9bfa14a9191d306f2bb3ae3f/DTDL/v4/DTDL.mqtt.v2.md?plain=1#L122

This is the doc on Mqtt extension v2, which is usable with both DTDL v3 and DTDL v4.

**Comment by rido-min** [comment]
> This is the doc on Mqtt extension v2, which is usable with both DTDL v3 and DTDL v4.

sure, but since this doc is under v4 folder I was expecting all samples use v4

**Comment by rido-min** [comment]
> The third column in this table indicates that this extension is usable in DTDL v2 only.

confusing, if it's not available in v4, it should not be listed in a v4 doc IMHO.

**Review by rido-min — APPROVED** [review]

**Comment by jrdouceur** [comment]
> > This is the doc on Mqtt extension v2, which is usable with both DTDL v3 and DTDL v4.
>
> sure, but since this doc is under v4 folder I was expecting all samples use v4

> > The third column in this table indicates that this extension is usable in DTDL v2 only.
>
> confusing, if it's not available in v4, it should not be listed in a v4 doc IMHO.

I think this is an issue of where the extension docs should go.  I am not particularly fond of having these docs under specific DTDL version folders, but that was the decision when we released DTDL v3.  We could define a different doc folder structure at some point, but I think this is separable from releasing DTDL v4.

**Pull request merged**
